const maritimeFlowGraph = {
    "nodes": [
        { "id": "EU", "name": "EU", "y": 49, "x": 12 },
        { "id": "US", "name": "USA: East coast", "y": 36.8, "x": -75.6 },
        { "id": "GB", "name": "UNITED KINGDOM", "y": 55, "x": -2 },
        { "id": "NO", "name": "NORWAY", "y": 61, "x": 8 },
        { "id": "CN", "name": "CHINA", "y": 39, "x": 103 },
        { "id": "BR", "name": "BRAZIL", "y": -5, "x": -55 },
        { "id": "TR", "name": "TÜRKIYE", "y": 39, "x": 35 },
        { "id": "EG", "name": "EGYPT", "y": 26.5, "x": 30 },
        { "id": "RU", "name": "RUSSIA: BLACK SEA", "y": 44.6, "x": 38.9 },
        { "id": "CA", "name": "Canada: East coast", "y": 49, "x": -60 },
        { "id": "LY", "name": "LIBYA", "y": 26.3, "x": 17.2 },
        { "id": "DZ", "name": "ALGERIA", "y": 28, "x": 3 },
        { "id": "MA", "name": "MOROCCO", "y": 34, "x": -4 },
        { "id": "NG", "name": "NIGERIA", "y": 9.1, "x": 8.7 },
        { "id": "UA", "name": "UKRAINE", "y": 49, "x": 35 },
        { "id": "IN", "name": "INDIA", "y": 22, "x": 79 }],
    "links": [
        { "source": "US", "target": "EU", "value": 172.4, "meta": { "direction": "Inwards", "partner": "US", "label": "USA: East coast", "share": 0.087 } },
        { "source": "EU", "target": "GB", "value": 110.4, "meta": { "direction": "Outwards", "partner": "GB", "label": "UNITED KINGDOM", "share": 0.055 } },
        { "source": "NO", "target": "EU", "value": 109.4, "meta": { "direction": "Inwards", "partner": "NO", "label": "NORWAY", "share": 0.055 } },
        { "source": "GB", "target": "EU", "value": 96.2, "meta": { "direction": "Inwards", "partner": "GB", "label": "UNITED KINGDOM", "share": 0.048 } },
        { "source": "CN", "target": "EU", "value": 79.1, "meta": { "direction": "Inwards", "partner": "CN", "label": "CHINA", "share": 0.04 } },
        { "source": "BR", "target": "EU", "value": 79.1, "meta": { "direction": "Inwards", "partner": "BR", "label": "BRAZIL", "share": 0.04 } },
        { "source": "TR", "target": "EU", "value": 78.5, "meta": { "direction": "Inwards", "partner": "TR", "label": "TÜRKIYE", "share": 0.039 } },
        { "source": "EG", "target": "EU", "value": 64.2, "meta": { "direction": "Inwards", "partner": "EG", "label": "EGYPT", "share": 0.032 } },
        { "source": "EU", "target": "US", "value": 48.5, "meta": { "direction": "Outwards", "partner": "US", "label": "USA: East coast", "share": 0.024 } },
        { "source": "RU", "target": "EU", "value": 44.7, "meta": { "direction": "Inwards", "partner": "RU", "label": "RUSSIA: BLACK SEA", "share": 0.022 } },
        { "source": "EU", "target": "TR", "value": 42.5, "meta": { "direction": "Outwards", "partner": "TR", "label": "TÜRKIYE", "share": 0.021 } },
        { "source": "CA", "target": "EU", "value": 39, "meta": { "direction": "Inwards", "partner": "CA", "label": "Canada: East coast", "share": 0.02 } },
        { "source": "LY", "target": "EU", "value": 36.3, "meta": { "direction": "Inwards", "partner": "LY", "label": "LIBYA", "share": 0.018 } },
        { "source": "DZ", "target": "EU", "value": 34.9, "meta": { "direction": "Inwards", "partner": "DZ", "label": "ALGERIA", "share": 0.018 } },
        { "source": "EU", "target": "MA", "value": 33.8, "meta": { "direction": "Outwards", "partner": "MA", "label": "MOROCCO", "share": 0.017 } },
        { "source": "NG", "target": "EU", "value": 33.3, "meta": { "direction": "Inwards", "partner": "NG", "label": "NIGERIA", "share": 0.017 } },
        { "source": "EU", "target": "CN", "value": 32.6, "meta": { "direction": "Outwards", "partner": "CN", "label": "CHINA", "share": 0.016 } },
        // { "source": "EU", "target": "ZZ09", "value": 29.2, "meta": { "direction": "Outwards", "partner": "ZZ09", "label": "UNKNOWN MCA", "share": 0.015 } },
        { "source": "UA", "target": "EU", "value": 27.2, "meta": { "direction": "Inwards", "partner": "UA", "label": "UKRAINE", "share": 0.014 } },
        { "source": "IN", "target": "EU", "value": 26, "meta": { "direction": "Inwards", "partner": "IN", "label": "INDIA", "share": 0.013 } }]
}